import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Chọn các độ đậm bạn cần
  variable: "--font-roboto-condensed", // Tạo biến CSS cho Tailwind
});
export const metadata: Metadata = {
  title: "Shop LMHT - Mua Bán ACC LOL & Liên Minh Uy Tín Giá Tốt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`robotoCondensed.variable`}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
